apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    nfs-subdir-external-provisioner: server
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      labels:
        nfs-subdir-external-provisioner: server
      name: "nfs-subdir-external-provisioner-{{cluster}}"
      namespace: argocd
    spec:
      destination:
        namespace: storage
        server: in-cluster
      project: default
      source:
        repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
        chart: nfs-subdir-external-provisioner
        targetRevision: 4.0.18
        helm:
          releaseName: nfs-provisioner
          values: |
            storageClass:
              defaultClass: true
              name: nfs
              nfs:
                server: 192.168.124.13
                path: /kubernetes
      syncPolicy:
        syncOptions:
          - PruneLast=false
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=false
          - Validate=false
      revisionHistoryLimit: 2
